PAKISTANI_FOODS = [
    {"name": "Chapati (Whole Wheat)", "iron_mg": 1.5, "protein_g": 3.0, "fat_g": 0.5, "calories": 120},
    {"name": "Paratha", "iron_mg": 1.2, "protein_g": 4.0, "fat_g": 12.0, "calories": 290},
    {"name": "Naan", "iron_mg": 1.0, "protein_g": 8.0, "fat_g": 5.0, "calories": 260},
    {"name": "White Rice (Boiled)", "iron_mg": 0.2, "protein_g": 2.5, "fat_g": 0.2, "calories": 130},
    {"name": "Chicken Biryani", "iron_mg": 1.8, "protein_g": 18.0, "fat_g": 11.0, "calories": 480},
    {"name": "Chicken Pulao", "iron_mg": 1.5, "protein_g": 16.0, "fat_g": 9.0, "calories": 400},
    {"name": "Chicken Karahi", "iron_mg": 2.1, "protein_g": 22.0, "fat_g": 14.0, "calories": 320},
    {"name": "Nihari (Beef)", "iron_mg": 3.5, "protein_g": 25.0, "fat_g": 22.0, "calories": 450},
    {"name": "Haleem (Beef/Chicken)", "iron_mg": 2.8, "protein_g": 20.0, "fat_g": 12.0, "calories": 350},
    {"name": "Seekh Kebab (Beef)", "iron_mg": 2.5, "protein_g": 18.0, "fat_g": 14.0, "calories": 220},
    {"name": "Chicken Tikka (Breast)", "iron_mg": 1.2, "protein_g": 28.0, "fat_g": 5.0, "calories": 180},
    {"name": "Shami Kebab (Beef)", "iron_mg": 1.8, "protein_g": 12.0, "fat_g": 8.0, "calories": 150},
    {"name": "Daal Mash (Cooked)", "iron_mg": 1.6, "protein_g": 7.0, "fat_g": 4.0, "calories": 160},
    {"name": "Daal Mong/Masoor (Cooked)", "iron_mg": 2.0, "protein_g": 8.0, "fat_g": 3.0, "calories": 150},
    {"name": "Aloo Palak", "iron_mg": 2.5, "protein_g": 3.0, "fat_g": 6.0, "calories": 140},
    {"name": "Aloo Gobhi", "iron_mg": 1.0, "protein_g": 2.5, "fat_g": 5.0, "calories": 120},
    {"name": "Bhindi Masala", "iron_mg": 1.2, "protein_g": 2.0, "fat_g": 5.0, "calories": 110},
    {"name": "Boiled Egg", "iron_mg": 0.9, "protein_g": 6.0, "fat_g": 5.0, "calories": 78},
    {"name": "Egg Omelette (with onions/chilies)", "iron_mg": 1.2, "protein_g": 7.0, "fat_g": 9.0, "calories": 120},
    {"name": "Beef Keema", "iron_mg": 3.0, "protein_g": 24.0, "fat_g": 16.0, "calories": 280},
    {"name": "Saag (Mustard Greens)", "iron_mg": 3.0, "protein_g": 3.0, "fat_g": 8.0, "calories": 150},
    {"name": "Samosa (Potato)", "iron_mg": 0.8, "protein_g": 3.5, "fat_g": 10.0, "calories": 200},
    {"name": "Pakora (Mixed Vegetable)", "iron_mg": 1.1, "protein_g": 4.0, "fat_g": 12.0, "calories": 250},
    {"name": "Yogurt (Plain, Full Fat)", "iron_mg": 0.1, "protein_g": 3.5, "fat_g": 3.25, "calories": 60},
    {"name": "Cucumber Salad", "iron_mg": 0.2, "protein_g": 0.6, "fat_g": 0.1, "calories": 15},
    {"name": "Apple", "iron_mg": 0.1, "protein_g": 0.3, "fat_g": 0.2, "calories": 95},
    {"name": "Banana", "iron_mg": 0.3, "protein_g": 1.1, "fat_g": 0.3, "calories": 105},
    {"name": "Mango", "iron_mg": 0.2, "protein_g": 0.8, "fat_g": 0.4, "calories": 150},
    {"name": "Guava", "iron_mg": 0.3, "protein_g": 2.5, "fat_g": 1.0, "calories": 68},
    {"name": "Orange", "iron_mg": 0.1, "protein_g": 0.9, "fat_g": 0.1, "calories": 62},
    {"name": "Dates (3 pieces)", "iron_mg": 1.0, "protein_g": 1.8, "fat_g": 0.15, "calories": 200},
    {"name": "Almonds (10 pieces)", "iron_mg": 0.4, "protein_g": 2.5, "fat_g": 6.0, "calories": 70},
    {"name": "Walnuts (5 whole)", "iron_mg": 0.3, "protein_g": 2.0, "fat_g": 9.0, "calories": 90},
    {"name": "Cow Milk (1 cup)", "iron_mg": 0.1, "protein_g": 8.0, "fat_g": 8.0, "calories": 150},
    {"name": "Chai (Standard with Milk & Sugar)", "iron_mg": 0.1, "protein_g": 2.0, "fat_g": 2.5, "calories": 90},
    {"name": "Fried Fish", "iron_mg": 1.5, "protein_g": 20.0, "fat_g": 12.0, "calories": 240},
    {"name": "Lobia (Black-eyed peas curry)", "iron_mg": 2.5, "protein_g": 9.0, "fat_g": 4.0, "calories": 180},
    {"name": "Chana Masala", "iron_mg": 2.2, "protein_g": 7.0, "fat_g": 5.0, "calories": 160},
    {"name": "Palak Paneer", "iron_mg": 2.0, "protein_g": 9.0, "fat_g": 12.0, "calories": 190},
    {"name": "Alu Muttar", "iron_mg": 1.1, "protein_g": 3.0, "fat_g": 5.0, "calories": 130},
    {"name": "Chicken Salan (Curry)", "iron_mg": 1.5, "protein_g": 18.0, "fat_g": 10.0, "calories": 250},
    {"name": "Kofta Curry (Beef)", "iron_mg": 2.8, "protein_g": 20.0, "fat_g": 16.0, "calories": 300},
    {"name": "Gajar Ka Halwa", "iron_mg": 0.6, "protein_g": 4.0, "fat_g": 14.0, "calories": 350},
    {"name": "Kheer", "iron_mg": 0.2, "protein_g": 5.0, "fat_g": 6.0, "calories": 250},
    {"name": "Raita (Yogurt with herbs)", "iron_mg": 0.1, "protein_g": 2.0, "fat_g": 2.0, "calories": 40},
    {"name": "Pista (Pistachios, 10 pieces)", "iron_mg": 0.5, "protein_g": 2.0, "fat_g": 5.5, "calories": 60},
    {"name": "Mutton Karahi", "iron_mg": 2.8, "protein_g": 24.0, "fat_g": 18.0, "calories": 350},
    {"name": "Tandoori Roti", "iron_mg": 1.2, "protein_g": 3.5, "fat_g": 0.3, "calories": 110},
    {"name": "Lassi (Sweet)", "iron_mg": 0.1, "protein_g": 4.5, "fat_g": 4.0, "calories": 180},
    {"name": "Watermelon (1 cup slices)", "iron_mg": 0.4, "protein_g": 0.9, "fat_g": 0.2, "calories": 46}
]
